from __future__ import annotations

import json
from sqlalchemy.orm import Session

from .models import User, Food
from .auth import get_password_hash


def seed_data(db: Session) -> None:
    if db.query(User).count() == 0:
        user = User(
            phone="13800000000",
            email="liming@example.com",
            password_hash=get_password_hash("123456"),
            nickname="李明",
            avatar="https://images.unsplash.com/photo-1591530347006-82116c5bf6d9?w=100&h=100&fit=crop",
            gender="男",
            age=28,
            height=175,
            weight=72,
            activity_level="中度活动",
            health_conditions=json.dumps(["无特殊健康状况"], ensure_ascii=False),
            allergies=json.dumps(["无已知过敏"], ensure_ascii=False),
            goal_type="减脂",
            target_weight=65,
            weekly_target=0.5,
            daily_calorie_goal=1870,
            nutrition_goals=json.dumps({"protein": 120, "fat": 60, "carbs": 220}, ensure_ascii=False),
            bmr=1756,
            tdee=2370,
            bmi=23.5,
            bmi_category="正常",
        )
        db.add(user)

    if db.query(Food).count() == 0:
        foods = [
            Food(
                name="鸡胸肉（清蒸）",
                brand="",
                category="肉类",
                image="https://images.unsplash.com/photo-1762631383378-115f2d4cbe07?w=80&h=80&fit=crop",
                barcode="690000001",
                calories=165,
                protein=31,
                fat=3.6,
                carbs=0,
                fiber=0,
                sugar=0,
                sodium=74,
                potassium=256,
                additives=json.dumps([], ensure_ascii=False),
                additive_count=0,
                ingredients="鸡胸肉",
                allergens=json.dumps([], ensure_ascii=False),
                health_score=9.0,
                nova_class=1,
                glycemic_index=0,
                glycemic_load=0,
                protein_quality=0.9,
                weight_loss_score=9.2,
                muscle_gain_score=9.0,
                diabetes_score=9.5,
                hypertension_score=8.8,
            ),
            Food(
                name="燕麦（即食）",
                brand="桂格",
                category="主食",
                image="https://images.unsplash.com/photo-1645545532196-e867a6ed4ad9?w=80&h=80&fit=crop",
                barcode="690000002",
                calories=367,
                protein=13,
                fat=6.9,
                carbs=66,
                fiber=10,
                sugar=1.2,
                sodium=5,
                potassium=362,
                additives=json.dumps(["无"], ensure_ascii=False),
                additive_count=0,
                ingredients="燕麦",
                allergens=json.dumps(["麸质"], ensure_ascii=False),
                health_score=8.0,
                nova_class=1,
                glycemic_index=55,
                glycemic_load=13,
                protein_quality=0.7,
                weight_loss_score=8.5,
                muscle_gain_score=7.8,
                diabetes_score=7.5,
                hypertension_score=8.0,
            ),
            Food(
                name="全脂牛奶",
                brand="蒙牛",
                category="乳制品",
                image="https://images.unsplash.com/photo-1642339800099-921df1a0a958?w=80&h=80&fit=crop",
                barcode="690000003",
                calories=65,
                protein=3.3,
                fat=3.8,
                carbs=4.8,
                fiber=0,
                sugar=5.0,
                sodium=43,
                potassium=150,
                additives=json.dumps(["无"], ensure_ascii=False),
                additive_count=0,
                ingredients="生牛乳",
                allergens=json.dumps(["乳制品"], ensure_ascii=False),
                health_score=7.0,
                nova_class=1,
                glycemic_index=30,
                glycemic_load=4,
                protein_quality=0.7,
                weight_loss_score=7.0,
                muscle_gain_score=7.2,
                diabetes_score=7.0,
                hypertension_score=7.2,
            ),
            Food(
                name="草莓蛋白棒",
                brand="Quest",
                category="零食",
                image="https://images.unsplash.com/photo-1772589668083-ae7b80e700ad?w=80&h=80&fit=crop",
                barcode="690000004",
                calories=190,
                protein=21,
                fat=7,
                carbs=21,
                fiber=10,
                sugar=2,
                sodium=170,
                potassium=90,
                additives=json.dumps(["代糖", "膳食纤维"], ensure_ascii=False),
                additive_count=2,
                ingredients="乳清蛋白、膳食纤维、草莓粉",
                allergens=json.dumps(["乳制品"], ensure_ascii=False),
                health_score=7.0,
                nova_class=3,
                glycemic_index=40,
                glycemic_load=6,
                protein_quality=0.8,
                weight_loss_score=7.2,
                muscle_gain_score=8.2,
                diabetes_score=6.8,
                hypertension_score=6.5,
            ),
            Food(
                name="可口可乐",
                brand="可口可乐",
                category="饮品",
                image="https://images.unsplash.com/photo-1676300186673-615bcc8d5d68?w=80&h=80&fit=crop",
                barcode="690000005",
                calories=43,
                protein=0,
                fat=0,
                carbs=10.6,
                fiber=0,
                sugar=10.6,
                sodium=5,
                potassium=2,
                additives=json.dumps(["焦糖色素", "磷酸"], ensure_ascii=False),
                additive_count=2,
                ingredients="碳酸水、糖、焦糖色素",
                allergens=json.dumps([], ensure_ascii=False),
                health_score=2.0,
                nova_class=4,
                glycemic_index=65,
                glycemic_load=7,
                protein_quality=0.1,
                weight_loss_score=2.0,
                muscle_gain_score=1.5,
                diabetes_score=1.0,
                hypertension_score=2.0,
            ),
        ]
        db.add_all(foods)

    db.commit()
